### ISSUE TITLE
Is there any gcc/clang implementation support for zilsd extension

### ISSUE THREAD

**Issue by fanghuaqi** [riscv/riscv-zilsd#12]
Hi there,

I've been scouring through existing patches for GCC and Clang, but haven't come across any mention of zilsd support. I was wondering if anyone in the community has any knowledge about whether zilsd is currently supported by either compiler or if there are any ongoing efforts to integrate it.

Any information or pointers would be greatly appreciated!

Thanks

**Comment by christian-herber-nxp** [comment]
we are working on publishing llvm and gcc support. Will post here when done.

**Comment by fanghuaqi** [comment]
> we are working on publishing llvm and gcc support. Will post here when done.

Hi @christian-herber-nxp , thanks for the info.

**Comment by christian-herber-nxp** [comment]
You can find a first prototype under: https://github.com/nxp-auto-tools/llvm-project/tree/Zilsd/release/17.x
There are some known issues, which are resolved when moving to LLVM 18. We will deliver another update soon to address this.

**Comment by fanghuaqi** [comment]
> You can find a first prototype under: https://github.com/nxp-auto-tools/llvm-project/tree/Zilsd/release/17.x There are some known issues, which are resolved when moving to LLVM 18. We will deliver another update soon to address this.

Thank you

**Comment by christian-herber-nxp** [comment]
In addition, we have meanwhile published gcc (https://github.com/nxp-auto-tools/gcc_zilsd/tree/zilsd) and binutils (https://github.com/nxp-auto-tools/binutils_zilsd/tree/zilsd) support.

**Comment by fanghuaqi** [comment]
> In addition, we have meanwhile published gcc (https://github.com/nxp-auto-tools/gcc_zilsd/tree/zilsd) and binutils (https://github.com/nxp-auto-tools/binutils_zilsd/tree/zilsd) support.

Got it, thanks.
