### ISSUE TITLE
Clarifications of the instructions in the specification

### ISSUE THREAD

**Issue by anderslindgren-iar** [riscv/riscv-zilsd#13]
Overall, I think this is a good proposition. However, the actual specification needs some additional work, from a pedagogical view.

Remember that the specification will be read by many people with varied background. Hence, it must include things that you and I might consider obvious. Concretely, an absolute majority of the readers will be people using assembly -- only a fraction of the readers will be hardware implementors, so it should be written from their point of new.

Background: I'm a compiler engineer at IAR and the author of the IAR compiler for RISC-V. I also participated in the definition of the RISC-V Zce (code size) extension. I have read instruction specifications for 35+ years.

## The syntax of the instructions are not defined

A good specification of an assembly instruction should start with the *syntax* -- the name of the instruction and the placement of the operands.

Currently, the only place where the syntax of, say, `ld` is it described is indirectly as the the result of expanding the compressed instructions.

## The description is hardware-centric

From the point of view of an assembly programmer the following sentence doesn't really make sense:

> It computes an effective address by adding the zero-extended offset, scaled by 8, to the stack pointer, x2.

How the offset is stored in the opcode is an encoding issue, and the steps the hardware takes to extract it is irrelevant for programmers.

A better wording would be "It computes the effective address by adding the offset to the stack pointer, x2".

## The range of `offset` is not specified

Presumably, this is the same range as the corresponding RV64 instructions. However, a reader should not need to look up that in another part of document -- in fact, most users will not know that that would be the place to look.

## Example

> `c.ld dst, offset(src)`
>
> Load a 64 bit value into the registers `dst` and `dst+1` from the memory location `offset` + `src`. `offset` must be a multiple of eight in the range 0 .. 248.

**Comment by christian-herber-nxp** [comment]
I believe the most confusion is coming from the fact that the encodings are not actually included. 
The reason for not including them is that we are reusing existing encodings. 
There is precedent for this in Zfinx, where the F instructions are also not reintroduced, but it is just stated that the existing instructions will use the x registers.
I am open to adding the encodings, if there is a consensus to have this.

The concrete wording around address calculation is directly mapping to a wording from the C extension. See e.g. 

> C.LWSP loads a 32-bit value from memory into register rd. It computes an effective address by adding
the zero-extended offset, scaled by 4, to the stack pointer, x2

As I cannot change that wording, consistency trumps here.
