### ISSUE TITLE
Alignment requirements for RV32 ld/sd

### ISSUE THREAD

**Issue by ghghost** [riscv/riscv-zilsd#16]
Since these instructions appear to be defined as doing two 32-bit memory accesses, do they require 4-byte alignment (as I believe is the case for all other RV32 instructions, except for D extension), or 8-byte? Perhaps the answer should be obvious, but I'd request that it be mentioned explicitly.

**Comment by tovine** [comment]
It's the same as all other memory accesses - misaligned accesses are permitted, but raising a misaligned trap is also a valid outcome.
I see it's not mentioned in this proposal text, but my original one had more details on this topic: https://github.com/tovine/riscv-rv32zild/blob/master/rv32zild_proposal.adoc#instructions
> Regarding accesses that are not naturally 2*XLEN-aligned, this extension will follow the example given by the base ISA; _**misaligned accesses are not required to raise an address-misaligned exception, but raising such an exception in this case is perfectly valid behavior**_, and atomicity is not mandated for such misaligned accesses.
For best performance across different implementations, software should make sure that load/store-pair instructions are only generated with 2*XLEN-aligned addresses.

Maybe something similar should be added here as well, to clarify on this point?

Obviously the atomicity part has been dropped so disregard the part with "and atomicity is not mandated for such misaligned accesses"

**Comment by ghghost** [comment]
> It's the same as all other memory accesses - misaligned accesses are
> permitted, but raising a misaligned trap is also a valid outcome.

Sorry, apparently my comment wasn't clear.  What happens on misalignment is
clear across the entire ISA: the issue is whether the instructions require
2XLEN alignment or only XLEN alignment.  I understand that 2XLEN is
appropriate, but I was concerned because of the italicized paragraph just
before section 2.1, which says that two (not "to") memory operations may be
required.

I still would request adding a sentence somewhere (perhaps in this
paragraph) that says something like "Note that even if the implementation
cracks the 2XLEN-size operation into two XLEN-size operations, 2XLEN
alignment is required."

This paragraph also says atomicity is not required when storing, and IMO
should also say whether or not atomicity is required when loading: the fact
that the registers must be written atomically doesn't necessarily require
that multiple memory accesses be done atomically.  Atomicity is a separate
issue from alignment, of course.

-- 

    L Peter Deutsch :: Aladdin Enterprises :: Healdsburg, CA & Burnaby, BC

**Comment by christian-herber-nxp** [comment]
> Since these instructions appear to be **defined as doing two 32-bit memory accesses**, do they require 4-byte alignment (as I believe is the case for all other RV32 instructions, except for D extension), or 8-byte? Perhaps the answer should be obvious, but I'd request that it be mentioned explicitly.

This is a misconception. The instructions are defined to access a doubleword. It is very explicit that the access size is 64b, and this is driving the alignment requirements.
In case an implementation does not have the ability to perform 64b accesses, it may indeed perform 2x 32b accesses (or 8x 8b accesses for that matter).

A good precedent is RV32 FLD and FSD.

**Comment by christian-herber-nxp** [comment]
mailing list comment by @allenjbaum:

> Should there be some mention her regarding what happens when the effective address is misaligned to the size of the 8B operand?
> (Even if the expectation is that it should be handled just as if this were a ld/sd op on an RV64 - that should at least be mentioned)

**Comment by christian-herber-nxp** [comment]
> mailing list comment by @allenjbaum:
> 
> > Should there be some mention her regarding what happens when the effective address is misaligned to the size of the 8B operand?
> > (Even if the expectation is that it should be handled just as if this were a ld/sd op on an RV64 - that should at least be mentioned)

I am careful not to over specify here. I think the existing specifications have this covered. I do think it might make sense to add a note
In my opinion, this is covered in the existing specification:

Unprivileged spec:
> Regardless of EEI, loads and stores whose effective addresses are naturally aligned shall not raise an
> address-misaligned exception. Loads and stores whose effective address is not naturally aligned to the
> referenced datatype (i.e., the effective address is not divisible by the size of the access in bytes) have
> behavior dependent on the EEI.

Privileged spec:
> On some implementations, misaligned loads, stores, and instruction fetches may also be decomposed
> into multiple accesses, some of which may succeed before a page-fault exception occurs. In particular,
> a portion of a misaligned store that passes the exception check may become visible, even if another
> portion fails the exception check. The same behavior may manifest for stores wider than XLEN bits
> (e.g., the FSD instruction in RV32D), even when the store address is naturally aligned.

There two questions in this thread:
1. What is the natural alignment? It is determined by the data type, which is a double, and thus it is 64b alignment
2. What happens when this is not the case? The same thing that happens on any access that is misaligned: It is EEI defined, and can involve hardware cracking or emulation via a trap.

**Comment by tovine** [comment]
Even though it's good to not overwhelm the readers with information on topics that are already technically covered by other parts of the specification, I think it's also good to add small notes where there's likely to be some uncertainty and confusion - such as in this case.

Sometimes it's better to include a little bit "too much" info (even though it might seem obvious to us) than to leave room for interpretation and misunderstanding, and while requiring readers to cross-reference with other specifications is not unreasonable, it _does_ make for a more pleasant user experience if typical questions are just answered on the spot by a small note.

Perhaps something like this (or with more condensed language)?
> Regarding accesses that are not naturally 64-bit aligned, this extension will follow the example given by the base ISA; misaligned accesses are not required to raise an address-misaligned exception, but raising such an exception in this case is perfectly valid behavior.
For best performance across different implementations, software should make sure that load/store-pair instructions are only generated with 64-bit aligned addresses.

**Comment by christian-herber-nxp** [comment]
I added https://github.com/riscv/riscv-zilsd/pull/17, which is a in my opinion a reasonable note to add without going to deep into reiterating previous texts.
