### ISSUE TITLE
Misalignment fault allowed on non-doubleword aligned address?

### ISSUE THREAD

**Issue by jklockars** [riscv/riscv-zilsd#22]
While the specification talks about reading/writing doublewords, it is not clear (to me at least), if the instructions are actually intended to work the same as ld/sd and thus be allowed to cast misalignment faults for non-8-byte aligned addresses.

Are these doubleword load/store instructions that happen to use two registers as destinations/sources, or are they a pair of adjacent word accesses?

**Comment by christian-herber-nxp** [comment]
I believe this was discussed and improved in the documentation here. I am closing the issue as duplicate. If you believe you were raising a different issue that has not yet been addressed, please reopen the issue.

**Comment by jklockars** [comment]
Ah, yes, missed the closed issues, somehow...
Thanks!
