### ISSUE TITLE
Comments on version 0.9.0

### ISSUE THREAD

**Issue by ved-rivos** [riscv/riscv-zilsd#29]
Chapter 2:
1. "The Zilsd & Zcmlsd extensions provide load/store pair instructions for RV32 analogous to RV64 doubleword load/store instructions, reusing the existing RV64 encodings.". This statement could be reworded to "The Zilsd & Zcmlsd extensions provide load/store pair instructions for RV32 analogous , reusing the existing RV64 doubleword load/store instruction encodings". This slightly avoids the implication that there are analogous pair instructions in RV64.

Section 2.1:
1. Using `offset` in the mnemonic is preferred than `simm`
3. This non-normative text "Therefore, implementations are not required to ensure atomicity when storing to memory. However, writing to both registers written by a 64-bit load must happen atomically to ensure fault handling is possible." implies that the 64-bit load needs to be atomic. This could be reworded to "For the purpose of raising misaligned-address or access exceptions, the address is considered to be naturally aligned if it is a multiple of 8.  Even if naturally aligned, the memory access might not be performed atomically.  If the address is a multiple of 4, then each 4-byte access is performed atomically. The `LD` instruction must however write the loaded data to the pair of destination registers atomically to ensure fault handling is possible."

Section 2.2:
1. Using `offset` in the mnemonic is preferred than `uimm`

Section 2.4:
1. Replace core with hart.
2. The second paragraph seems to imply that xTVAL is updated only on an access fault and not on other types of faults such as a page fault. The second paragraph however not required as trap delivery is well defined and this specification does not extend that.

Section 2.6
1. "Software should only use these instructions on non-idempotent memory regions when software can  tolerate the required memory accesses being issued repeatedly in the case that they cause exceptions." This text is a bit misleading as the region cannot be non-idempotent if repeated accesses can be tolerated. That said this whole section can be deleted as the allowance of  redoing the memory access has been discussed in earlier sections at length and this property is not different than the existing FLD/FSD for RV32.

**Comment by christian-herber-nxp** [comment]
@ved-rivos: I very much appreciate the comments and will take care to address the raised issues. As we have the specification entered into ARC review, I need to determine a good moment to do so.

**Comment by christian-herber-nxp** [comment]
> 1. Using `offset` in the mnemonic is preferred than `simm`

I chose this to have it consistent with Zcb. I can change it, but then there should also be a motion to change this on Zcb to have it consistent

**Comment by christian-herber-nxp** [comment]
> 2\. This non-normative text "Therefore, implementations are not required to ensure atomicity when storing to memory. However, writing to both registers written by a 64-bit load must happen atomically to ensure fault handling is possible." implies that the 64-bit load needs to be atomic.

The load is not required to happen atomically. It can be broken down into e.g. byte accesses. However, the D-word must be written atomically to the register

**Comment by christian-herber-nxp** [comment]
> 1. "Software should only use these instructions on non-idempotent memory regions when software can  tolerate the required memory accesses being issued repeatedly in the case that they cause exceptions." This text is a bit misleading as the region cannot be non-idempotent if repeated accesses can be tolerated. That said this whole section can be deleted as the allowance of  redoing the memory access has been discussed in earlier sections at length and this property is not different than the existing FLD/FSD for RV32.

The text was included so that the reader does not have to read the D extension to understand Zilsd. It is also closely aligned with Zcmp.

**Comment by christian-herber-nxp** [comment]
> 1. Replace core with hart.

Agree that this is how it should be. In this context, Zcmp does also use the word core, so it may need to be addressed there also. Fixing through https://github.com/riscv/riscv-zilsd/pull/30

**Comment by ved-rivos** [comment]
> The load is not required to happen atomically. It can be broken down into e.g. byte accesses. However, the D-word must be written atomically to the register

We would not want to provide that freedom to break it into byte accesses. If the address is a multiple of 4, then each 4-byte access should be performed atomically. The suggested text is addressing that aspect.

**Comment by christian-herber-nxp** [comment]
> > The load is not required to happen atomically. It can be broken down into e.g. byte accesses. However, the D-word must be written atomically to the register
> 
> We would not want to provide that freedom to break it into byte accesses. If the address is a multiple of 4, then each 4-byte access should be performed atomically. The suggested text is addressing that aspect.

It was an explicit request of the ARC at the initiation of the specification that atomicity is not a hard requirement. In particular, it should be possible to implement Zilsd on harts with a 32b memory interface, which forces you to break the load.

**Comment by ved-rivos** [comment]
> It was an explicit request of the ARC at the initiation of the specification that atomicity is not a hard requirement. In particular, it should be possible to implement Zilsd on harts with a 32b memory interface, which forces you to break the load.

I am part of ARC and this feedback is from ARC. The text suggested did not require atomicity for 64 bits. I will repeat the text here: For the purpose of raising misaligned-address or access exceptions, the address is considered to be naturally aligned if it is a multiple of 8. **Even if naturally aligned, the memory access might not be performed atomically. If the address is a multiple of 4, then each 4-byte access is performed atomically.** The LD instruction must however write the loaded data to the pair of destination registers atomically to ensure fault handling is possible."

**Comment by christian-herber-nxp** [comment]
thanks for the clarification. to be honest, I am not up to speed with the current ARC composition, and even then it is good to clarify when speaking on behalf of the ARC. The only reference to ARC I can google is this https://wiki.riscv.org/display/TECH/Architecture+Review and it does not have you listed.
For traceability reasons, it is also good to make one issue per review point. 
I will create those on your behalf, so that we trace those and make sure we get conclusion on all of those.

**Comment by tovine** [comment]
> Section 2.1:
>
>    Using offset in the mnemonic is preferred than simm
>    This non-normative text "Therefore, implementations are not required to ensure atomicity when storing to memory. However, writing to both registers written by a 64-bit load must happen atomically to ensure fault handling is possible." implies that the 64-bit load needs to be atomic. This could be reworded to "For the purpose of raising misaligned-address or access exceptions, the address is considered to be naturally aligned if it is a multiple of 8. Even if naturally aligned, the memory access might not be performed atomically. If the address is a multiple of 4, then each 4-byte access is performed atomically. The LD instruction must however write the loaded data to the pair of destination registers atomically to ensure fault handling is possible."

I think this sentence could be worded a bit differently:
> If the address is a multiple of 4, then each 4-byte access is performed atomically.

To me this reads as if trapping a 4-byte aligned access as misaligned is not allowed, which is not the intention; forcing simple implementations with 64 bit data bus interface to crack these instructions into multiple micro ops (including buffering to do the atomic register update) would add quite a bit of extra complexity and make it less attractive to implement in those cases.

EDIT: I just saw that this has already been split out and mentioned in https://github.com/riscv/riscv-zilsd/issues/34
We can continue the discussion there.

**Comment by christian-herber-nxp** [comment]
closing this issue as all items have been moved into separate issues
