### ISSUE TITLE
Zclsd is incompatible with Zcm*

### ISSUE THREAD

**Issue by arichardson** [riscv/riscv-zilsd#49]
These extensions occupy the same opcode space although https://github.com/riscv/riscv-zilsd/issues/44#issuecomment-2317122762 says that Zcm* is expected to be implemented by systems with Zisld:

> The other thing I would like to add is that machines which implement Zilsd are likely to implement Zcmp, so optimizing prologue/epilogue does not sound promising to me.

Is Zclsd still useful? I've filed #48 to call out this incompatibility explicitly.

**Comment by christian-herber-nxp** [comment]
Zclsd is not incompatible with Zcm*.
It reuses Zcf while Zcm* reuses Zcd encodings.

**Comment by arichardson** [comment]
Sorry about this, looks like I misread the spec - I thought it replaced the zcf instructions.
