### ISSUE TITLE
Question about debug Abstract Command Access Register Behavior when Zilsd extension present for RV32

### ISSUE THREAD

**Issue by fanghuaqi** [riscv/riscv-zilsd#50]
Hi @kasanovic @christian-herber-nxp ,

I have a question about when we implement `Zilsd` extension in RV32IMAC target, for the debug module, if we use Abstract command -> Access Register to access a GPR such as X0 as below:

![image](https://github.com/user-attachments/assets/be5f6a28-a5e8-4f64-b546-02ea79719983)

If the `aarsize` is 3(64bit), will this command still fail, or can be ok now if we have `Zilsd` extension, for RTL implementation, previous this register access  64bit is translated `ld`, for `RV32IMAC`, this will fail, but for `RV32IMAC_Zilsd`, the `ld` instruction now present, so register access 64bit seems to be ok now.

So here I want to confirm, what the real behavior for `rv32imac_zilsd` ISA processor to do register access for 64bit, will it still fail or return ok?

Thanks
Huaqi

**Comment by tovine** [comment]
Good question, but I think it's safe to assume that a 64-bit access to a register should still fail since the size of the actual registers doesn't change with this extension - it only gives you the opportunity to use them in pairs for memory accesses.

**Comment by fanghuaqi** [comment]
> Good question, but I think it's safe to assume that a 64-bit access to a register should still fail since the size of the actual registers doesn't change with this extension - it only gives you the opportunity to use them in pairs for memory accesses.

Ok, thanks for your reply, if this is confirmed, maybe we can add it in this spec.

**Comment by fanghuaqi** [comment]
Hi @christian-herber-nxp ， do you have any comments on this issue

**Comment by christian-herber-nxp** [comment]
I agree with what was said. The l registers are still 32 bit, so you cannot access the lowest 64 bit of a register. Should still fail.

**Comment by fanghuaqi** [comment]
> I agree with what was said. The l registers are still 32 bit, so you cannot access the lowest 64 bit of a register. Should still fail.

Ok, got it. Thanks
