### ISSUE TITLE
missing specification of Endian behavior

### ISSUE THREAD

**Issue by ubc-guy** [riscv/riscv-zilsd#9]
The ld instruction operates on a pair of registers, eg rd and rd+1. However, it is not clear which register holds the more signficant bits. Should rd be treated as though it is requivalent to a lower byte address and hold the most significant bits on a big endian configuration?

Likewise for sd.

**Comment by tovine** [comment]
How is it defined for the RV64 `ld` and `sd` instruction? We'll want to follow the same here, including treating rd as the lower half and rd+1 as the upper.

**Comment by christian-herber-nxp** [comment]
The spec currently states:

> Regardless of endianness, the lower-numbered register holds the low-order bits, and the higher-numbered register holds the high-order bits: e.g., bits 31:0 of an operand in Zilsd might be held in register x14, with bits 63:32 of that operand held in x15.

This is the same behavior as in Zdinx.

**Comment by ubc-guy** [comment]
oops - sorry i missed that - should have searched on "endian"

**Comment by ubc-guy** [comment]
oops - sorry i missed that - should have searched on "endian"
